# Generated by Django 5.1 on 2024-08-15 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
            options={
                'db_table': 'user_detail',
                'indexes': [models.Index(fields=['user'], name='user_detail_user_id_45022b_idx')],
            },
        ),
    ]
