name: Deploy Django App to AWS EC2

on:
  push:
    branches:
      - main  # Deploy when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Prepare SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
        chmod 600 /tmp/deploy_key
        # Verify key content for troubleshooting (remove in production)
        # cat /tmp/deploy_key

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          cd /home/ubuntu/Confiure-github-workflow || exit 1
          git pull origin main || exit 1
          source venv/bin/activate || exit 1
          pip install -r requirements.txt || exit 1
          python manage.py migrate || exit 1
          python manage.py collectstatic --noinput || exit 1
          sudo systemctl restart gunicorn || exit 1
          sudo systemctl restart nginx || exit 1
        EOF
        rm /tmp/deploy_key

    - name: Notify Deployment
      run: echo "Deployment to EC2 completed successfully."
